swagger: '2.0'
info:
  title: coisas erradas PoC
  description: |
    COISAS ERRADAS
paths:
  /tempest:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
